ORDER_WAITING_PAYMENT = 'wp'
ORDER_SHIPPING_FEE_REQUESTED = 'rf'
ORDER_PROCESSING = 'op'
ORDER_SHIPPED = 'os'

SHIPPING_COMPANY_FEDEX = 'FEDX'
SHIPPING_COMPANY_USPS = 'USPS'
SHIPPING_COMPANY_UPS = 'UPS'
SHIPPING_COMPANY_DHL = 'DHL'

SHIPPING_STANDARD = 'SS'
SHIPPING_EXPEDITED = 'SE'
SHIPPING_SAME_DAY = 'SSD'
SHIPPING_INTERNATIONAL = 'SI'

SHIPPING_COMPANIES = (
    (SHIPPING_COMPANY_FEDEX, 'FEDEX'),
    (SHIPPING_COMPANY_USPS, 'USPS'),
    (SHIPPING_COMPANY_UPS, 'UPS'),
    (SHIPPING_COMPANY_DHL, 'DHL')
)

SHIPPING_COMPANIES_DICT = dict(SHIPPING_COMPANIES)

SHIPPING_OPTIONS = (
    (SHIPPING_STANDARD, 'Shipping Standard'),
    (SHIPPING_EXPEDITED, 'Shipping Expedited'),
    (SHIPPING_SAME_DAY, 'Shipping Same day'),
    (SHIPPING_INTERNATIONAL, 'International Shipping')
)

ORDER_STATUS = (
    (ORDER_WAITING_PAYMENT, "Waiting Payment"),
    (ORDER_SHIPPING_FEE_REQUESTED, "Shipping fee Requested"),
    (ORDER_PROCESSING, "Processing order"), #PAID
    (ORDER_SHIPPED, "Shipped"),
)