ORDER_WAITING_PAYMENT = 'wp'
ORDER_SHIPPING_FEE_REQUESTED = 'rf'
ORDER_PROCESSING_ORDER = 'rf'
ORDER_SHIPPED = 'dl'

SHIPPING_COMPANY_FEDEX = 'FEDX'
SHIPPING_COMPANY_USPS = 'USPS'
SHIPPING_COMPANY_UPS = 'UPS'
SHIPPING_COMPANY_DHL = 'DHL'

SHIPPING_STANDARD = 'SS'
SHIPPING_EXPEDITED = 'SE'
SHIPPING_SAME_DAY = 'SSD'
SHIPPING_INTERNATIONAL = 'SI'