CONFIRMED = "Confirmed"
SUSPENDED = "Suspended"
FAILED = "Failed"

CREDITS = 'credits'
AUCTION = 'auction'
BUYITNOW = 'buyitnow'


ORDER_NOT_PAID = "n"
ORDER_PAYMENT_REVIEWING = "r"
ORDER_PAID = "p"
ORDER_CANCELLED = "c"
ORDER_FINISHED = "f"
ORDER_SUSPENDED = "s"


PLIMUS = 'p'
FACEBOOK_CREDITS = 'f'
DALPAY = 'd'
