AUCTION_WAITING = 'w'
AUCTION_PROCESSING = 'p'
AUCTION_PAUSE = 's'
AUCTION_JUST_ENDED = 'e'
AUCTION_FINISHED = 'f'
AUCTION_WAITING_PAYMENT = 'm'
AUCTION_PAID = 'd'
AUCTION_COMPLETED = 'c'

AUCTION_WAITING_PLEDGE = 'w'
AUCTION_FINISHED_NO_PLEDGED = 'x'
AUCTION_SHOWCASE = 'p'

BID_NORMAL = 'n'
BID_MATIC = 'm'

